name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el c√≥digo del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Paso 3: Instalar Surge.sh
      - name: Install Surge
        run: npm install -g surge

      # Paso 4: Desplegar a Surge.sh usando el token
      - name: Deploy to Surge
        run: surge ./ parcial-surge-ci-braya.surge.sh --token ${{ secrets.SURGE_TOKEN }}
